modLoader = "javafml"
loaderVersion = "[46,)"

license = "All Rights Reserved"
issueTrackerURL = ""
showAsResourcePack = false

[[mods]]
modId = "greatworld"
version = "1.0.1.0"
displayName = "Great World"
updateJSONURL = "https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
displayURL = "https://space.bilibili.com/1346025280"
logoFile = "logo.png"
credits = "thank deepseek"
authors = "friedfish"
description = '''
  the main mod in the modpack
    '''
displayTest = "MATCH_VERSION"

[[dependencies.greatworld]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.greatworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
